### ISSUE TITLE
Confidence Intervals

### ISSUE THREAD

**Issue by samleighton87** [BavoDC/CalibrationCurves#2]
The function val.prob.ci.2 calculates the 95% confidence intervals around the intercept, slope and auc. It presents them on the plot. Is it possible for the function to also return these values? At present it returns a number of stats including the intercept, slope and auc but without confidence intervals.

**Comment by BavoDC** [comment]
This is indeed possible and a good idea! I will implement it when I have some time to work on it. If you need these values in the meantime, you can look at line 373 (https://github.com/BavoDC/val.prob.ci.2/blob/master/val.prob.ci.2.R#L373). This is where you find the objects in which these values are stored.

You can for example adjust the val,.prob.ci.2 function to return the stats.2 instead of the stats object (https://github.com/BavoDC/val.prob.ci.2/blob/master/val.prob.ci.2.R#L425) . To make sure that everything works:
`environment(ValProbAdj) = as.environment(environment(val.prob.ci.2))` where ValProbAdj is the name of the adjusted function. Hope this helps you in the meantime

**Comment by samleighton87** [comment]
Thanks a lot. I just added this to the function:
`stats_ci <- list("stats" = stats, "cl.interc" = cl.interc, "cl.slope" = cl.slope, "cl.auc" = cl.auc)`
`return(stats_ci)`
