### ISSUE TITLE
Propose to add _"miscalibration"_ plot

### ISSUE THREAD

**Issue by mafed** [BavoDC/CalibrationCurves#6]
Instead of plotting `y` _vs._ `x` in the calibration plot, drawing `y–x` _vs._ `x` gives a _miscalibration_ plot, which is focusing on what is most interesting: deviation from equality.
I think it's an easy modification and might be worth it.

**Comment by proshano** [comment]
I like this idea!
________________________________
From: Federico Mattiello ***@***.***>
Sent: Sunday, August 27, 2023 9:56:46 AM
To: BavoDC/CalibrationCurves ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [BavoDC/CalibrationCurves] Propose to add _"miscalibration"_ plot (Issue #6)


Instead of plotting y vs. x in the calibration plot, drawing y–x vs. x gives a miscalibration plot, which is focusing on what is most interesting: deviation from equality.
I think it's an easy modification and might be worth it.

**Comment by BavoDC** [comment]
Hi Federico,

This sounds like an interesting idea! I haven't heard of it before, but it definitely sounds useful. I added it to my to-do list.

Which references would you suggest for the miscalibration plot? I can then look at it in detail.

Best,

Bavo.

**Comment by mafed** [comment]
Hi Bavo,
I actually don't have any reference for this.
It's just an idea I had during a project where I was validating a model.
It shifts the focus to what we're really looking at: deviations from the
bisector line.

Cheers,
Federico

**Comment by BavoDC** [comment]
Hi Federico,

Thanks again for the suggestion. Unfortunately, due to lack of time, I will have to postpone it until later.

Best,

Bavo.
